service:
  enableTrieCompress: true
  enableTrieInverted: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone:
spring:
#  单机和主从配置
  redis:
    host: 152.136.154.249
    port: 6379
    password: 123456
#    sentinel:
      #redis-哨兵集群的配置
#      master: mymaster
      #哨兵节点
#      nodes:
#      password:
#    lettuce:
#      pool:
#        # 连接池最大连接数(使用负值表示没有限制) 默认为8
#        max-active: 8
#        # 连接池最大阻塞等待时间(使用负值表示没有限制) 默认为-1
#        max-wait: -1
#        # 连接池中的最大空闲连接 默认为8
#        max-idle: 8
#        # 连接池中的最小空闲连接 默认为 0
#        min-idle: 0
