service:
  enableTrieCompress: true
  enableTrieInverted: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://10.200.2.1:10000/eureka/,http://10.200.6.38:10000/eureka/,http://10.200.3.163:10000/eureka/
#spring:
#  boot:
#    admin:
#      url: http://10.200.2.1:10001