######################################DEV JSERVER CONFIG########################################
#这是开发站的JServer配置  开发环节的TIDB配置不需要兄弟们更改，可直接拷贝
wdp:
  server:
    addresses:
#      - ip: 10.202.16.165
#        port: 8899
#      - ip: 10.202.16.148
#        port: 8899
      - ip: "10.202.105.76"
        port: 8899
    connectTimeout: 3
    readTimeout: 120
  client:
#    appName: wdp-client-test-jdbc
#    instanceId: 18
#    instanceKey: 01uLrd8bMJ1X4dronAxYkOIF8lhkRByz
    appName: "Wind.BDG.NewsSendSuper"
    instanceId: "0011"
    instanceKey: "01QAorpy50fRTnUSXujpJtLxaIHQ1234"
  
######################################TEST JSERVER CONFIG ########################################

#这是测试站的JServer配置，需要单独申请
#wdp:
#  server:
#    connectTimeout: 3
#    readTimeout: 60
#    addresses:
#      - ip: "10.200.8.29"
#        port: 8899
#  client:
#    "appName": "Wind.WDP.ImageOCR.FI"
#    "instanceId": "0333"
#    "instanceKey": "01toFLF5lQWpEiLsFY74wFEXJ9ZfOWfP"
#    "ipAddress": "10.200.127.107"


##################################PRD JSERVER CONFIG############################################

# empty